### PR TITLE
fix camelCase, and add PascalCase

### LINKED ISSUE #50: wrong camel case
camel case should look like `camelCase` not `CamelCase`, the latter is callled pascal case

### PR DESCRIPTION
**Pull request by ccoVeille**
- **fix: camelCase was using PascalCase**
- **feat: add PascalCase**

Fixes #50

### CODE REVIEW

**Comment by ccoVeille** [comment]
cc @sibouras

**Comment by ccoVeille** [comment]
I'll need to check a few things. That's why I marked the PR as draft

**Comment by ccoVeille** [comment]
code is ok now

**Comment by sibouras** [comment]
that was fast thanks!

**Comment by abhimanyu003** [comment]
Once again thanks so much for your work @ccoVeille 
I will do a tag release soon.

**Pull request merged**
