### PR TITLE
Add flag to process string directly

### LINKED ISSUE #3: Suggestion: add possibility to process the texts directly
I would like to see a flag that makes it possible to process the texts directly, without going through the menu. I think this would be quite useful to use the tool e.g. in scripts.

### PR DESCRIPTION
**Pull request by rverst**
This adds a flag to use the processors directly, without going through the menu, e.g:  
`sttr -i "Hello World" -p reverse`

Resolves #3

### CODE REVIEW

**Comment by abhimanyu003** [comment]
Hello @rverst honestly I was thinking about the same thing.
Thanks so much for your work on code updates.

Can we have a flag alias as well like `b64-enc, base64-encode` both will work.

```
sttr-i "Hello World" -p b64-enc
sttr -i "Hello world" -p base64-encode // alias of b64-enc
```

Let me know your thoughts.

**Comment by rverst** [comment]
Hi @abhimanyu003, that's a good idea, I think. I've added that by simply using a slice for the arguments, so multiple aliases are possible for each processor.
I also thought the flag for the string is not really necessary in my opinion, that could be passed as a simple (positional) argument: `sttr -p md5 "Hello World”`. And maybe a flag for using a file as input might be nice?

**Comment by abhimanyu003** [comment]
@rverst your change are looking good, I will merge these soon and update things.
What I personally is we can provide flag anywhere and not in specific sequence and it should work.
```go
sttr "some text" -p md5  // 552e21cd4cd9918678e3c1a0df491bc3
sttr  -p md5 "some text" // 552e21cd4cd9918678e3c1a0df491bc3
```

Yes, i'm also thinking about files, I will try to work on that over weekends.

**Comment by rverst** [comment]
Sounds good, maybe you'll have a look on [flaggy](https://github.com/integrii/flaggy), it's a nice cli-flag parser and could handle the positional argument as you suggest.

```golang
  ...
  var input string
  var proc string
  
  flaggy.SetName("sttr")
  flaggy.SetVersion(version)
   

  flaggy.String(&proc, "p", "process", "The process to be used")  
  flaggy.AddPositionalValue(&input, "text", 1, false, "The text to process")
  flaggy.Parse()
  ...
)
```

**Comment by fervic** [comment]
@abhimanyu003 very nice and handy tool!

@rverst  I like your suggestion for a non-interactive mode so the tool can be used in bash scripts.

>  And maybe a flag for using a file as input might be nice?

IMHO, the non-interactive version should use STDIN/STDOUT redirect:

```
$ echo "some text" | sttr -p md5
552e21cd4cd9918678e3c1a0df491bc3
```

Additionally, because its sole purpose is to convert, then maybe what's not necessary is the `-p` flag and it becomes a subcommand (like how `git` works):

```
$ sttr md5 (waits for STDIN)
> "some text" (hit enter)
552e21cd4cd9918678e3c1a0df491bc3
```

```
$ echo "some text" | sttr md5
552e21cd4cd9918678e3c1a0df491bc3
```
Or for current behavior, when a subcommands isn't provided:
```
$ echo "some text" | sttr
(prompts for processor to use)
```

I suggest taking a look at [Cobra](https://github.com/spf13/cobra). Many big CLI projects in Go use it.

**Comment by fervic** [comment]
I apologize I hadn't seen the multiple operations feature `/`. It would've been killed with the subcommand approach I suggested in my previous comment.

Unless it is a special subcommand: `multi` that receives a list of processors but I don't think it would make it a great design.

Maybe the processors should continue to be specified with a `-p` flag. That way they can always be 0 or N; where 0 continues to mean _interactive_.

**Comment by rverst** [comment]
@fervic, I really like your idea of making this a "real" CLI tool. In my opinion, this is the bigger use case for such a tool. Don't get me wrong, the interactive menu is nice, but usually, you want to process the output and not copy it manually from the terminal.

> I apologize I hadn't seen the multiple operations feature `/`. It would've been killed with the subcommand approach I suggested in my previous comment.

I think you may have got this wrong, as far as I can see the `/` is just for filtering the list in interactive mode, this seems to be the default [binding of the bubbletea list](https://github.com/charmbracelet/bubbles/blob/0ac5ecdf8170df53c057b079cca315ac77c31d16/list/keys.go#L61).  
But I think this might be a nice feature as well: `echo "Hello World" | sttr -p lower -p sha256`

Let's see what @abhimanyu003  thinks about putting more focus on the CLI part. Cobra would be great for that, my suggestion for flaggy was because it requires far fewer changes to the structure :-)  
If he agrees, I will make appropriate changes to the pull request in the next few days.

**Comment by abhimanyu003** [comment]
Hello @rverst and @fervic 
Thanks for having in-depth communications and sharing ideas.

*Please let me know what you guys think about this*

Here are my thoughts and plans

* **Is CLI in focus:**
    * Yes 100%
    * If you provide direct processing flag, we skip the `menu` and return the result right away.
    ```
        echo "some text" | sttr -p md5
        
        // 552e21cd4cd9918678e3c1a0df491bc3
        
        sttr -i "some text" -p md5
    
        // 552e21cd4cd9918678e3c1a0df491bc3
    ```
    * If no input is provided it should promot for the input and open up the ui-menu.

    ```
        sttr
        // promot form input
        // then menu
    ```

* **Is UI-Menu in focus:**
    * Yes, because many times you can't remember the flag and many people are not expert with CLI, it should be quick and easy for them.
    * `/` is just filter in ui-menu which is the default binding of the bubbletea list.
    * running `sttr` with no flags should prompt for input and open up the UI-menu after that.

* **Plan to support files:**
    * Yes.
    * But I guess it will be only for CLI ( for now )
    
    ```
        sttr -f "sample.txt" -o "sample.json"
        
        sttr -f "sample.txt" > "sample.json"
    ```

**Comment by fervic** [comment]
Hello @abhimanyu003 and @rverst, here's a list of suggestion (happy to contribute, not only make recommendations :slightly_smiling_face:).

1. Make it CLI centric, not TUI centric nor both. TUI would be a special mode, not the default.
2. Work with STDIN and STDOUT by default.
3. Instead of using `-f`, let's take the input file from the last argument, just like `cat`, `sort`, `md5sum`, `grep`, `sed`, etc. do.
4. Forget about the thought of applying many at the same time. Once it works with STDIN/STDOUT, the same result can be achieved by linking more than one command call with pipe (or vertical bar): `echo "Hello World" | sttr -p lower | sttr -p sha256`
5. Because of 4., then the processor can become a sub-command and not a flag `sttr md5`. (I'll expand on the advantages further down)
6. When calling it with plain `sttr`, it prints the [usage message](https://github.com/spf13/cobra/blob/master/user_guide.md#usage-message).
7. When calling it with the "interactive" sub-command, it displays the UI Menu: `sttr interactive`. IMO "interactive" mode needs to be intentional because I'm thinking on a scripting scenario in which you accidentally forget to provide flags and it would just prompt and hang. Plus as @rverst stated about non-interactive: _"(...) is the bigger use case for such a tool."_

**Advantages of 5. (provided by Cobra):**
- If a processor requires special flags, Cobra can handle it. I'm making up this processor so I can have an example: `echo "123" | sttr zeropad -n 5  --> "00123"` or `echo "12" | sttr zeropad -n 3 --> "012"`
- @abhimanyu003's concern about people not remembering the flag can be addressed by [this Cobra feature](https://github.com/spf13/cobra/blob/master/shell_completions.md).
- Save on keystrokes by not having to type `-f` each time :grinning: 

I acknowledge that importing Cobra is a big decision, not only because of the changes required in the current structure but because it is a big library with many features. Additionally, I don't like the design proposed by Cobra (package vars) but I already worked around it in a project and I can contribute with that.

On the flip side some of the features are really worth it, such as what I've already mentioned plus automatic help/tool usage generation, plus handling flags. It is also very easy to continue adding sub-commands, re-use flags that work for all, isolate those that don't, etc.

Please let me know in which points both of you agree/disagree.

Thanks for reading this far!

**Comment by rverst** [comment]
Well, I did a little something ;-)

- I moved the user interface out into a separate package and added Cobra for command processing. I restructured the processors a bit (basically made a processor interface) and built a generator for the individual processor instructions - the individual commands for each processor are generated with `go generate`.   
- Passing values from stdin works, so piping multiple instructions is no problem.  
- The user interface is available via the `interactive` command. The user interface also starts by simply typing `sttr` or typing text without the `echo "Hello World" | sttr` command.  
- Support for custom flags for the processors has also been implemented.

@abhimanyu003, @fervic please let me know your thoughts about this approach. There is still a lot to do, the handling of the stdin with no arguments provided needs to be done as well as file reading. The tests could also use some love, I have only roughly adapted them to the new process structure.

**Comment by fervic** [comment]
> Well, I did a little something ;-)

A little??? 😆 

You did it all!

**Comment by abhimanyu003** [comment]
Oh wow, @rverst this is pure gold.

I'm very good with this structure, initially, I was a little worried about having sub-flags.
But your JSON and ZeroPad are doing it very gracefully.

I'm going to merge this to `v0.2` branch, also *I have given you access.*

**Feedback**

* Do we have to push the generated files to git, we can use GitHub actions here during the build. I'm not fully sure how it will impact direct go installs yet. 

```
go install github.com/abhimanyu003/sttr@latest
```

**Comment by rverst** [comment]
Thank’s a lot, for the kudos and the access 😀

The zeropad processor still has a few quirks, I think it makes more sense to use the flag to specify the width of the result, not the number of zeros appended. But it was late yesterday 😉.

As for the generated files, so far I've always versioned stuff like that. I think that makes the code more understandable when you look at it on github for example. The date I would take out there but still (has no real sense) and tweak the template a little, so that gofmt/gofumpt is satisfied with it, then there are not constantly changes when you regenerate the files.

**Pull request merged**
